version: "3"
services:
  back-end:
    build: .
    command: npm run start
    volumes:
      - .:/wayfinder-back-end
      - /wayfinder-back-end/node_modules
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    # command: npm run start-prod

    ports:
      - "5000:5000"

    depends_on:
      - db

    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/wayfinder

  db:
    build:
      context: ./
      dockerfile: Dockerfile_db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: wayfinder
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
